### ISSUE TITLE
Plugin?

### ISSUE THREAD

**Issue by ghost** [DashMedia/SlackNotify#2]
So this could be used as a plugin, to automatically send notifications upon certain events?

**Comment by JayCarney** [comment]
Essentially, yes. We're using it to send error reports to a #error-log channel when something goes wrong with form submissions on our websites. 

I kind of think of it as a helper extra, it's kind of pointless on it's own, but it does a lot of ground work for you to save working directly with Slacks API. 

So inside of a plugin attached to an event you could have:

```
$text = 'Event fired:' . $modx->event->name;

$modx->runSnippet('SlackNotify', array(
    'text'=> $text
));
```

Or if you want to use slacks "attachments" feature

```
$text = 'Message from : ' . $modx->getOption('site_name');
$attachments = array();
$attachments[] = array(
    'key'=> 'Event',
    'value'=> $modx->event->name
);
$modx->runSnippet('SlackNotify', array(
    'text'=> $text,
    'fields'=>json_encode($attachments)  //needs to be in JSON to support being used as a snippet in chunks/templates
));
```
